# Generated by Django 5.2.5 on 2025-09-09 09:03

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0210_macaddress_ordering'),
        ('extras', '0129_fix_script_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikrotikDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('foo', models.CharField(max_length=50)),
                ('bar', models.CharField(max_length=50)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='netbox_mikrotik_mikrotik_device', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'netbox_mikrotik_device',
                'ordering': ['device__name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
