# Generated by Django 5.2.5 on 2025-09-16 09:12

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0210_macaddress_ordering'),
        ('extras', '0129_fix_script_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikrotikDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=254)),
                ('address_list_sync', models.BooleanField(default=False)),
                ('dns_sync', models.BooleanField(default=False)),
                ('dhcp_sync', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mikrotik_device', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'netbox_mikrotik_device',
                'ordering': ['device__name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MikrotikDhcpServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64)),
                ('mikrotik_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mikrotik_dhcp_servers', to='netbox_mikrotik.mikrotikdevice')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'DHCP Server',
                'verbose_name_plural': 'DHCP Servers',
                'db_table': 'netbox_mikrotik_dhcp_server',
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MikrotikDhcpLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('mac_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netbox_mikrotik_dhcp_leases', to='dcim.macaddress')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('mikrotik_dhcp_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netbox_mikrotik_dhcp_leases', to='netbox_mikrotik.mikrotikdhcpserver')),
            ],
            options={
                'verbose_name': 'DHCP Lease',
                'verbose_name_plural': 'DHCP Leases',
                'db_table': 'netbox_mikrotik_dhcp_lease',
                'ordering': ['mac_address'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
